services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: raffyz-app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - raffyz-network

  nginx:
    image: nginx:alpine
    container_name: raffyz-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - raffyz-network

networks:
  raffyz-network:
    driver: bridge
